"""empty message

Revision ID: 91a7132fe61c
Revises: fc92ba2ffd7f
Create Date: 2016-06-11 11:03:09.563032

"""

# revision identifiers, used by Alembic.
revision = '91a7132fe61c'
down_revision = 'fc92ba2ffd7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
