"""Make hike date nullable

Revision ID: bce69b840145
Revises: 2532bc7051f3
Create Date: 2017-03-11 12:35:06.347344

"""

# revision identifiers, used by Alembic.
revision = 'bce69b840145'
down_revision = '2532bc7051f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hike', 'date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hike', 'date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    ### end Alembic commands ###
