"""empty message

Revision ID: f1d3540eda1e
Revises: f7888bd46c75
Create Date: 2017-03-05 14:20:59.810834

"""

# revision identifiers, used by Alembic.
revision = 'f1d3540eda1e'
down_revision = 'f7888bd46c75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_constraint(u'user_fb_id_key', 'user', type_='unique')
    op.drop_column('user', 'fb_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_fb_id_key', 'user', ['fb_id'])
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
