"""add-hikes

Revision ID: f7888bd46c75
Revises: 91a7132fe61c
Create Date: 2017-02-16 07:36:06.108806

"""

# revision identifiers, used by Alembic.
revision = 'f7888bd46c75'
down_revision = '91a7132fe61c'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hike_destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('high_point_coord', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=False),
    sa.Column('is_summit', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint(u"method in ('ski', 'foot', 'crampons', 'climb', 'via ferrata')"),
    sa.ForeignKeyConstraint(['destination_id'], [u'hike_destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hike')
    op.drop_table('hike_destination')
    ### end Alembic commands ###
