"""mark not null

Revision ID: fc92ba2ffd7f
Revises: 820bb005f2c5
Create Date: 2016-06-09 23:14:48.303280

"""

# revision identifiers, used by Alembic.
revision = 'fc92ba2ffd7f'
down_revision = '820bb005f2c5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_post', 'datetime_added',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('blog_post', 'raw_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('blog_post', 'rendered_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('blog_post', 'title',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_post', 'title',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('blog_post', 'rendered_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('blog_post', 'raw_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('blog_post', 'datetime_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###
